4 tooltips
buremba/rakam-landpage pull request #6
Opened 2018-11-13 19:14 UTC by sahindogan

Alt alta `<a href />` koyarak yaptım. 

Svg örneği de benzer mantıkla çalışıyor. Onun için tüm svg'yi sayfaya almak gerekiyor. O yüzden a href ile yaptım.

2018-11-13 20:59 UTC, buremba requested changes
Tooltip'lerin genislikliklerinin icindeki yaziya gore otomatik ayarlanmasini saglayabilir misin?

2018-11-13 21:22 UTC, buremba commented
bir de tooltiplerin marginlerini yuzde olarak vermen mumkun mu? bu sekilde genisligi artirdigimizda herhangi bir sorun yasamamis oluruz.

2018-11-16 10:50 UTC, sahindogan commented
Son güncellemeler tamamdır.

2018-11-18 17:15 UTC, buremba requested changes
https://cl.ly/a20250c03f9f
bu kismin temasi hala siyah, ayarlarindan beyaz bir temaya gecmen gerekiyor. ayrica sql renklendirilmiyor, muhtemelen o ayari yapilmamis

2019-01-13 23:04 UTC, buremba approved these changes

2019-01-13 23:04 UTC, merged